function [strf,varargout]=strfFwd(strf,datIdx)
%function [strf,varargout]=strfFwd(strf,datIdx)
%
% Gets predicted response for a stimulus and STRF model. 
%
% INPUT:
%	   [strf] = strf model structure
%    [datIdx] = a vector containing indices of the samples to be used in the 
%               fitting.
%
% OUTPUT:
%      [strf] = strf model structure
% [varargout] = Any other output generated by the STRF's fwd
%		        function (ex. response before output nonlinearity)
%
%
%(Some code modified from NETLAB)



fwdstr = [strf.type, 'Fwd'];
[s{1:nargout}]=feval(fwdstr,strf,datIdx);

strf = s{1};

if nargout > 1
  for i = 2:nargout
    varargout{i-1} = s{i};
  end
end
