function [strf,err,varargout] = midErr(strf,datIdx)
%MIDERR	Evaluate error function for generalized linear model.
%
%
%	Description:
%
%	E = MIDERR(STRF, STIM, RESP) takes a STRF structure, together with 
%	    the STIM and RESP matrices and returns the value of the error 
%	    function.
%
%	[E, VARARGOUT] = MIDERR(STRF, STIM, RESP) also returns any additional
%	return values from the error function.
%
%	Usage:
%	
%	[E, VARARGOUT] = MIDERR(STRF, STIM, RESP)
%
%
%	Inputs:
%
%	STRF,	A STRF structure
%	STIM,	An n X m stimulus matrix (or vector)
%	RESP,	An n X trials response matrix (or vector)
%
%
%	Outputs:
%
%	E, Value of the error function at W for a given STIM and RESP
%
%	VARARGOUT, Any other output generated by the STRF's fwd
%		   function (ex. response before output nonlinearity)
%
%
%(Some code modified from NETLAB)
global globDat;

% Check arguments for consistency

% [y, a] = midfwd(strf, x);
[strf,resp_strf,a]=midFwd(strf,datIdx);

x=[-strf.nbin*strf.bin:strf.bin:strf.nbin*strf.bin];
y=resp_strf;
s=globDat.stim;
r=globDat.resp(datIdx);

px=histc(y,x);
px(:)=px(:)/sum(px);
z=find(r>0);
pxr=histc(y(z),x);
pxr(:)=pxr(:)/sum(pxr);
z=find(pxr>0);
err=40-sum(pxr(z).*log(pxr(z)./(px(z))));

% e=err;


%[e, edata, eprior] = errbayes(strf, edata);
